name: 'Analyze Flutter'
description: 'Analyze your Flutter project''s Dart code'
author: 'Zennon Gosalvez'
inputs:
  fail-on-warnings:
    description: 'The action fails if any warning was found. This will always fail on errors. Optional. Default: `false`'
    default: false
  working-directory:
    description: 'The working directory. Optional. Default: `./`'
    default: ./
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'search'
  color: 'green'
