name: 'Analyze Flutter'
description: 'Analyze your Flutter project''s Dart code'
author: 'Zennon Gosalvez'
runs:
  using: "composite"
  steps: 
    - run: | # https://github.com/flutter/gallery/blob/master/.github/workflows/unit.yml
        flutter pub get
        flutter analyze
        flutter format --set-exit-if-changed --dry-run .
      shell: bash
branding:
  icon: 'search'
  color: 'green'
